### ISSUE TITLE
Does not work with Ruby 2.x

### ISSUE THREAD

**Issue by tobiasschuerg** [crowdin/crowdin-cli-v1#52]
Only works with Ruby 1.x and not 2.x (at least on Windows)

**Comment by Andrulko** [comment]
Seems everything works fine with Ruby 2.2.4 on Windows. Investigating this, sorry.

**Comment by kevinjalbert** [comment]
Just wanted to echo this. I'm on macOS.

Didn't work on Ruby version 2.3.0:

```
/Users/jalbert/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fee0d03a79c crowdin-cli-0.5.3> (NoMethodError)
    from /Users/jalbert/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
    from /Users/jalbert/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
    from /Users/jalbert/.rvm/gems/ruby-2.3.0/gems/crowdin-cli-0.5.3/bin/crowdin-cli:6:in `<top (required)>'
    from /Users/jalbert/.rvm/gems/ruby-2.3.0/bin/crowdin-cli:23:in `load'
    from /Users/jalbert/.rvm/gems/ruby-2.3.0/bin/crowdin-cli:23:in `<main>'
    from /Users/jalbert/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/jalbert/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

Bumped my Ruby version to 2.3.1 and it works now.

**Comment by mamantoha** [comment]
This is known issue with rubygems https://github.com/rubygems/rubygems/issues/1420

I think this should fix it:

```
$ gem update --system
```

**Comment by kevinjalbert** [comment]
Seems to do the trick for me! Thanks @mamantoha .

**Comment by tobiasschuerg** [comment]
Yes, it does.
